### ISSUE TITLE
Payment Select (re-Migrations)

### ISSUE THREAD

**Issue by AdamTomczyk** [LofftApp/lofft-mobile-app#36]
# Feature Request

## Feature description

ReMigration of Payment Select
- New Component dealing with selecting card payments

### Feature experience

I can select payment methods

### To-do

- [ ]  Create Component
- [ ]  Create RadioButtons
- [ ]  Implement Toggle Helpers

### Design

![](https://user-images.githubusercontent.com/86358155/148367298-4debf917-a164-4615-931b-f081fe51f72b.png)

**Comment by jhibbeard89** [comment]
## Update 29.08
The app is going through a refocus and this is now being put on hold.
