### ISSUE TITLE
Issue with Reloading and display polls when creating Poll

### ISSUE THREAD

**Issue by AdamTomczyk** [LofftApp/lofft-mobile-app#79]
**Describe the bug**
After the Poll is created a hot reload should be performed to ensure the display of newly created polls!

**To Reproduce**

1. Go to 'Managements'
2. Click on 'Create Poll'

**Expected behavior**
Should reload and display all the components correctly

**Additional context**

**Comment by jhibbeard89** [comment]
This was completed in previous PR and not closed
